language: go

go:
- 1.5
- 1.6

before_install:
- go get github.com/axw/gocov/gocov
- go get github.com/mattn/goveralls
- go get github.com/golang/lint/golint
- if ! go get code.google.com/p/go.tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi

script:
# Test Code quality
- go vet ./...
- $HOME/gopath/bin/golint ./...
- $HOME/gopath/bin/goveralls -service=travis-ci ./...

# Test buildable on most common platforms, beyond Linux
- GOOS=darwin go build ./...
- GOOS=windows go build ./...
